from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from datamodel_code_generator import InputFileType, OpenAPIScope, generate
from datamodel_code_generator.enums import DataModelType
from datamodel_code_generator.format import DatetimeClassType, Formatter, PythonVersion

from .errors import GenerationError
from .naming import pascal_case
from .parser.references import Resolver
from .parser.schemas import prepare_component_schemas


def generate_models(spec_path: Path, header: str, document: dict[str, Any]) -> str:
    schemas = prepare_component_schemas(document, Resolver(document))
    model_document = {
        **document,
        "components": {**document.get("components", {}), "schemas": schemas},
    }
    try:
        result = generate(
            json.dumps(model_document),
            input_file_type=InputFileType.OpenAPI,
            output_model_type=DataModelType.MsgspecStruct,
            openapi_scopes=[OpenAPIScope.Schemas],
            target_python_version=PythonVersion.PY_312,
            use_standard_collections=True,
            use_union_operator=True,
            use_annotated=True,
            field_constraints=True,
            strict_nullable=True,
            use_schema_description=True,
            custom_class_name_generator=pascal_case,
            disable_timestamp=True,
            formatters=[Formatter.BUILTIN],
            use_standard_primitive_types=True,
            output_datetime_class=DatetimeClassType.Datetime,
        )
    except Exception as error:
        raise GenerationError(f"cannot generate models from {spec_path}: {error}") from error
    if result is None:
        return f"{header}\n"
    if not isinstance(result, str):
        raise GenerationError("multi-module model output is not supported")
    generated_lines = [
        line
        for line in result.splitlines()
        if not line.startswith("# generated by datamodel-codegen:")
        and not line.startswith("#   filename:")
    ]
    return f"{header}\n" + "\n".join(generated_lines).lstrip() + "\n"
