import os
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path


def test_make_publish_updates_versions_and_tags_only_the_release(tmp_path: Path) -> None:
    source = Path(__file__).resolve().parents[3]
    repo = tmp_path / "repo"
    repo.mkdir()
    env = {
        **os.environ,
        "UV_CACHE_DIR": str(tmp_path / "uv-cache"),
        "UV_OFFLINE": "true",
        "UV_PYTHON": sys.executable,
        "UV_PYTHON_DOWNLOADS": "never",
        "GIT_CONFIG_GLOBAL": os.devnull,
        "GIT_CONFIG_NOSYSTEM": "1",
    }

    def run(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            args, cwd=repo, env=env, capture_output=True, text=True, check=False
        )
        if check:
            assert result.returncode == 0, result.stdout + result.stderr
        return result

    shutil.copyfile(source / "Makefile", repo / "Makefile")
    makefile = repo / "Makefile"
    initial = re.sub(r"^VERSION = .*$", "VERSION = 0.1.8", makefile.read_text(), flags=re.MULTILINE)
    makefile.write_text(initial)
    (repo / ".gitignore").write_text(".venv/\n")
    for directory, name in (
        (".", "workspace"),
        ("packages/oapi-gen", "oapi-gen"),
        ("packages/oapi-gen-dishka", "oapi-gen-dishka"),
    ):
        project = repo / directory / "pyproject.toml"
        project.parent.mkdir(parents=True, exist_ok=True)
        project.write_text(
            f'[project]\nname = "{name}"\nversion = "0.1.8"\nrequires-python = ">=3.12"\n'
        )
    with (repo / "pyproject.toml").open("a") as stream:
        stream.write('\n[tool.uv.workspace]\nmembers = ["packages/*"]\n')
    snapshot = repo / "packages/oapi-gen/tests/snapshots/cats/router.py.txt"
    snapshot.parent.mkdir(parents=True)
    body = "value = '0.1.8'\n"
    snapshot.write_text("# Generated by oapi-gen. DO NOT EDIT.\n" + body)
    manifest = snapshot.with_name(".oapi-gen-manifest.json.txt")
    manifest.write_text('{"version": 1}\n')
    run("uv", "lock")
    run("git", "init")
    run("git", "config", "user.name", "Release test")
    run("git", "config", "user.email", "release@example.invalid")
    run("git", "add", ".")
    run("git", "commit", "-m", "Initial state")
    assert "ruff check" in run("make", "--dry-run").stdout
    run("make", "publish")
    assert run("git", "cat-file", "-t", "refs/tags/v0.1.8").stdout.strip() == "tag"

    makefile.write_text(initial.replace("VERSION = 0.1.8", "VERSION = 0.1.9"))
    other = repo / "other.txt"
    other.write_text("Unrelated work\n")
    assert run("make", "publish", check=False).returncode != 0
    run("git", "add", "other.txt")
    assert run("make", "publish", check=False).returncode != 0
    run("git", "rm", "-f", "other.txt")
    assert run("git", "show", "HEAD:pyproject.toml").stdout == (repo / "pyproject.toml").read_text()

    makefile.write_text(initial.replace("VERSION = 0.1.8", "VERSION = 0.2.0-rc1"))
    assert "canonical" in run("make", "publish", check=False).stdout
    makefile.write_text(initial.replace("VERSION = 0.1.8", "VERSION = 0.1.9"))
    run("make", "publish")

    projects = [repo / "pyproject.toml", *repo.glob("packages/*/pyproject.toml")]
    assert all(tomllib.loads(p.read_text())["project"]["version"] == "0.1.9" for p in projects)
    assert {p["version"] for p in tomllib.loads((repo / "uv.lock").read_text())["package"]} == {
        "0.1.9"
    }
    assert snapshot.read_text() == "# Generated by oapi-gen. DO NOT EDIT.\n" + body
    assert manifest.read_text() == '{"version": 1}\n'
    assert run("git", "status", "--porcelain").stdout == ""
    assert run("git", "log", "-1", "--format=%s").stdout.strip() == "chore: release v0.1.9"
    assert run("git", "cat-file", "-t", "refs/tags/v0.1.9").stdout.strip() == "tag"
    assert (
        run("git", "rev-parse", "v0.1.9^{commit}").stdout == run("git", "rev-parse", "HEAD").stdout
    )
    assert "already exists" in run("make", "publish", check=False).stdout
    assert run("git", "rev-list", "--count", "HEAD").stdout.strip() == "3"
