from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path

import pytest
import yaml
from oapi_gen import CheckFailedError, check_package, generate_package, render_package

FIXTURE = Path(__file__).parent / "fixtures" / "cats.openapi.yaml"


def test_comments_and_declaration_order_do_not_change_generated_files(tmp_path: Path) -> None:
    document = yaml.safe_load(FIXTURE.read_text())
    # Preserve field order even when it differs from alphabetical order.
    cat = document["components"]["schemas"]["Cat"]
    cat["properties"] = dict(reversed(list(cat["properties"].items())))
    source = tmp_path / "api.yaml"
    source.write_text(yaml.safe_dump(document, sort_keys=False))
    output = tmp_path / "generated"
    generate_package(source, output)
    before = {p.relative_to(output): p.read_bytes() for p in output.rglob("*") if p.is_file()}

    source.write_text("# A documentation-only change\n" + source.read_text())
    check_package(source, output)
    document["paths"] = dict(reversed(list(document["paths"].items())))
    document["components"]["schemas"] = dict(
        reversed(list(document["components"]["schemas"].items()))
    )
    source.write_text(yaml.safe_dump(document, sort_keys=False))
    check_package(source, output)
    generate_package(source, output)

    assert {
        p.relative_to(output): p.read_bytes() for p in output.rglob("*") if p.is_file()
    } == before
    models = (output / "models.py").read_text()
    assert models.index("    name: str") < models.index("    id: UUID")
    manifest = json.loads((output / ".oapi-gen-manifest.json").read_text())
    assert "source_sha256" not in manifest
    assert (
        (output / "_runtime.py").read_text().startswith("# Generated by oapi-gen. DO NOT EDIT.\n")
    )


def test_changes_are_local_to_their_handler_group(tmp_path: Path) -> None:
    document = yaml.safe_load(FIXTURE.read_text())
    document["paths"]["/dogs"] = {
        "get": {
            "operationId": "listDogs",
            "tags": ["Dogs"],
            "responses": {"204": {"description": "No content"}},
        }
    }
    source = tmp_path / "api.yaml"

    def render(value):
        source.write_text(yaml.safe_dump(value, sort_keys=False))
        return render_package(source).files

    original = render(document)
    changed = deepcopy(document)
    changed["paths"]["/cats"]["get"]["summary"] = "List all cats"
    summary_files = render(changed)
    assert {name for name in original if original[name] != summary_files[name]} == {
        "contracts/cats.py",
        "openapi.json",
    }

    changed["paths"]["/cats"]["get"]["parameters"][0]["schema"]["maximum"] = 50
    parameter_files = render(changed)
    assert {name for name in original if original[name] != parameter_files[name]} == {
        "contracts/cats.py",
        "routes/cats.py",
        "openapi.json",
    }

    changed["paths"]["/cats/search"] = {
        "get": {
            "operationId": "searchCats",
            "x-handler-group": "Cats",
            "responses": {"204": {"description": "No content"}},
        }
    }
    operation_files = render(changed)
    assert {name for name in original if original[name] != operation_files[name]} == {
        "contracts/__init__.py",
        "contracts/cats.py",
        "routes/cats.py",
        "openapi.json",
    }
    changed["paths"]["/birds"] = {
        "get": {
            "operationId": "listBirds",
            "tags": ["Birds"],
            "responses": {"204": {"description": "No content"}},
        }
    }
    group_files = render(changed)
    for group in ("cats", "dogs"):
        for directory in ("contracts", "routes"):
            name = f"{directory}/{group}.py"
            assert group_files[name] == operation_files[name]


def test_migrates_flat_output_and_removes_retired_groups(tmp_path: Path) -> None:
    output = tmp_path / "generated"
    output.mkdir()
    legacy = output / "contracts.py"
    legacy.write_text("# Previous generated contracts\n")
    manifest = output / ".oapi-gen-manifest.json"
    manifest.write_text(json.dumps({"files": ["contracts.py"], "source_sha256": "old"}))
    generate_package(FIXTURE, output)
    assert not legacy.exists()
    contracts = output / "contracts/cats.py"
    assert contracts.is_file()
    contracts.write_text("# Stale nested file\n")
    with pytest.raises(CheckFailedError, match=r"contracts/cats\.py"):
        check_package(FIXTURE, output)
    generate_package(FIXTURE, output)

    user_file = output / "contracts/notes.txt"
    user_file.write_text("Keep this file\n")
    document = yaml.safe_load(FIXTURE.read_text())
    document["paths"] = {}
    source = tmp_path / "empty.yaml"
    source.write_text(yaml.safe_dump(document))
    generate_package(source, output)
    check_package(source, output)
    assert not contracts.exists()
    assert not (output / "routes/cats.py").exists()
    assert user_file.read_text() == "Keep this file\n"
