"""Write generated Python source and deterministic imports."""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager

from .._version import __version__
from ..ir import (
    ImportRef,
)


class Writer:
    def __init__(self) -> None:
        self._lines: list[str] = []
        self._imports: set[ImportRef] = set()
        self._indent = 0

    def require(self, module: str, name: str) -> None:
        self._imports.add((module, name))

    def line(self, value: str = "", indent: int = 0) -> None:
        self._lines.append(f"{'    ' * (indent + self._indent)}{value}" if value else "")

    @contextmanager
    def indented(self) -> Iterator[None]:
        self._indent += 1
        try:
            yield
        finally:
            self._indent -= 1

    def render(self) -> str:
        lines = self._lines.copy()
        position = (
            lines.index("from __future__ import annotations") + 1
            if "from __future__ import annotations" in lines
            else 1
        )
        lines[position:position] = [
            f"from {module} import {name}" for module, name in sorted(self._imports)
        ]
        return "\n".join(lines).rstrip() + "\n"


def generated_header(source_hash: str) -> str:
    return f"# Generated by oapi-gen {__version__}. DO NOT EDIT.\n# Source SHA256: {source_hash}"


def render_model_imports(writer: Writer, names: set[str]) -> None:
    for name in names:
        writer.require(".models", f"{name} as _models_{name}")


def render_imports(writer: Writer, imports: set[ImportRef]) -> None:
    for module, name in imports:
        writer.require(module, name)
