"""Update only the generator version in snapshot headers for a release."""

import tomllib
from pathlib import Path

project = Path(__file__).resolve().parents[1] / "packages/oapi-gen"
version = tomllib.loads((project / "pyproject.toml").read_text())["project"]["version"]
for snapshot in (project / "tests/snapshots").glob("*/*.py.txt"):
    header, newline, body = snapshot.read_text().partition("\n")
    if header.startswith("# Generated by oapi-gen "):
        snapshot.write_text(f"# Generated by oapi-gen {version}. DO NOT EDIT.{newline}{body}")
